environment:
  matrix:
    - nodejs_version: 18
    - nodejs_version: 16
    - nodejs_version: 14
    - nodejs_version: 12
    - nodejs_version: 10
    - nodejs_version: 9
    - nodejs_version: 8
    - nodejs_version: 6

platform:
  - x64

test_script:
  - node --version
  - yarn --version
  - npm test

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - npm install

matrix:
  fast_finish: true

build: false

version: '{build}'

shallow_clone: true

clone_depth: 1
